version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: jupyter nbconvert --to html Untitled.ipynb
          name: Creating artifacts
      - run:
          command: |
            mkdir tmp/;
            mv Untitled.html tmp/;
      - store_artifacts:
          path: tmp/
workflows:
  main:
    jobs:
      - build-and-test
